version: '3.8'

services:
  # MySQL Database
  mysql:
    image: mysql:8.0
    container_name: kaamsekaaam-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: kaamsekaaam
      MYSQL_USER: kaamuser
      MYSQL_PASSWORD: kaampassword
    ports:
      - '3306:3306'
    volumes:
      - mysql_data:/var/lib/mysql
      - ./database/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    healthcheck:
      test: [ 'CMD', 'mysqladmin', 'ping', '-h', 'localhost' ]
      timeout: 20s
      retries: 10

  # Node.js Backend
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: kaamsekaaam-backend
    restart: always
    environment:
      # server
      DB_HOST: mysql
      DB_USER: kaamuser
      DB_PASSWORD: kaampassword
      DB_NAME: kaamsekaaam
      # local
      # DB_HOST: localhost
      # DB_USER: root
      # DB_PASSWORD: password
      # DB_NAME: kaamsekaaam
      DB_PORT: 3306
      PORT: 5000
      NODE_ENV: production
      JWT_SECRET: your_super_secret_jwt_key_change_this
      SMTP_HOST: smtp.gmail.com
      SMTP_PORT: 587
      SMTP_USER: astonrecruitment64@gmail.com
      SMTP_PASSWORD: qwbd layp mrzy srci
      ADMIN_EMAIL: admin@kaamsekaaam.com
      ADMIN_PASSWORD_ENV: Admin@12345
      # FRONTEND_URL: http://localhost:5173
      FRONTEND_URL: https://astonrecruitment.in
    ports:
      - '5000:5000'
    depends_on:
      mysql:
        condition: service_healthy
    volumes:
      - ./backend/uploads:/app/uploads

  # React Frontend
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: kaamsekaaam-frontend
    restart: always
    ports:
      - '5173:5173'
    environment:
      VITE_API_URL: http://localhost:5000/api
    depends_on:
      - backend

volumes:
  mysql_data:
